"""new match data type for travel

Revision ID: 314e74343d0d
Revises: a79afead8188
Create Date: 2026-02-25 13:55:59.856296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314e74343d0d'
down_revision = 'a79afead8188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_team_data', schema=None) as batch_op:
        batch_op.alter_column('auto_traveled',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_team_data', schema=None) as batch_op:
        batch_op.alter_column('auto_traveled',
               existing_type=sa.String(length=50),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
