"""expand calculated_data for archived TBA and Statbotics stats

Revision ID: 825d5d39ba4b
Revises: 8defd42ffe78
Create Date: 2026-08-14 22:04:28.317389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825d5d39ba4b'
down_revision = '8defd42ffe78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calculated_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tba_rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))
        batch_op.alter_column('event_epa',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('event_opr',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('event_dpr',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('event_ccwm',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_calculated_data_team_event', ['team_number', 'event_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calculated_data', schema=None) as batch_op:
        batch_op.drop_constraint('uq_calculated_data_team_event', type_='unique')
        batch_op.alter_column('event_ccwm',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('event_dpr',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('event_opr',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('event_epa',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('last_updated')
        batch_op.drop_column('tba_rank')

    # ### end Alembic commands ###
