"""include human player in match

Revision ID: 8defd42ffe78
Revises: b4be902ab761
Create Date: 2026-03-13 15:05:58.216498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8defd42ffe78'
down_revision = 'b4be902ab761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_team_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alliance_human_fuel', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_team_data', schema=None) as batch_op:
        batch_op.drop_column('alliance_human_fuel')

    # ### end Alembic commands ###
