"""new table for event schedule

Revision ID: 9fb957ba9223
Revises: a9eb1286bfdb
Create Date: 2026-02-28 10:09:57.725339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb957ba9223'
down_revision = 'a9eb1286bfdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_schedule',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('match_type', sa.String(length=50), nullable=True),
    sa.Column('match_number', sa.Integer(), nullable=True),
    sa.Column('red_1_id', sa.Integer(), nullable=True),
    sa.Column('red_2_id', sa.Integer(), nullable=True),
    sa.Column('red_3_id', sa.Integer(), nullable=True),
    sa.Column('blue_1_id', sa.Integer(), nullable=True),
    sa.Column('blue_2_id', sa.Integer(), nullable=True),
    sa.Column('blue_3_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blue_1_id'], ['frc_teams.team_id'], ),
    sa.ForeignKeyConstraint(['blue_2_id'], ['frc_teams.team_id'], ),
    sa.ForeignKeyConstraint(['blue_3_id'], ['frc_teams.team_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['red_1_id'], ['frc_teams.team_id'], ),
    sa.ForeignKeyConstraint(['red_2_id'], ['frc_teams.team_id'], ),
    sa.ForeignKeyConstraint(['red_3_id'], ['frc_teams.team_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_year', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('event_year')

    op.drop_table('event_schedule')
    # ### end Alembic commands ###
