"""new match data columns

Revision ID: a79afead8188
Revises: 
Create Date: 2026-02-25 09:43:00.993224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79afead8188'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('red_1_auto_climb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('red_2_auto_climb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('red_3_auto_climb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blue_1_auto_climb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blue_2_auto_climb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blue_3_auto_climb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('red_1_endgame_climb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('red_2_endgame_climb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('red_3_endgame_climb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blue_1_endgame_climb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blue_2_endgame_climb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blue_3_endgame_climb', sa.Integer(), nullable=True))

    with op.batch_alter_table('match_team_data', schema=None) as batch_op:
        batch_op.alter_column('match_card',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('match_absent',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_team_data', schema=None) as batch_op:
        batch_op.alter_column('match_absent',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('match_card',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('match_data', schema=None) as batch_op:
        batch_op.drop_column('blue_3_endgame_climb')
        batch_op.drop_column('blue_2_endgame_climb')
        batch_op.drop_column('blue_1_endgame_climb')
        batch_op.drop_column('red_3_endgame_climb')
        batch_op.drop_column('red_2_endgame_climb')
        batch_op.drop_column('red_1_endgame_climb')
        batch_op.drop_column('blue_3_auto_climb')
        batch_op.drop_column('blue_2_auto_climb')
        batch_op.drop_column('blue_1_auto_climb')
        batch_op.drop_column('red_3_auto_climb')
        batch_op.drop_column('red_2_auto_climb')
        batch_op.drop_column('red_1_auto_climb')

    # ### end Alembic commands ###
