"""match FIRST teleop climb term

Revision ID: a9eb1286bfdb
Revises: 314e74343d0d
Create Date: 2026-02-25 16:49:47.586799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9eb1286bfdb'
down_revision = '314e74343d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_team_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endgame_climb_try', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('endgame_climb_level', sa.Integer(), nullable=True))
        batch_op.drop_column('teleop_climb_try')
        batch_op.drop_column('teleop_climb_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_team_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teleop_climb_level', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('teleop_climb_try', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('endgame_climb_level')
        batch_op.drop_column('endgame_climb_try')

    # ### end Alembic commands ###
