"""include human player

Revision ID: b4be902ab761
Revises: 
Create Date: 2026-03-11 18:52:09.551098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4be902ab761'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('red_human_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blue_human_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_data', schema=None) as batch_op:
        batch_op.drop_column('blue_human_score')
        batch_op.drop_column('red_human_score')

    # ### end Alembic commands ###
